B2bApp/urls.py
from django.urls import path
from B2bApp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name= 'B2bApp'
urlpatterns = [
              path('', views.HomeView.as_view(), name='home'),
              path('serach/', views.Serach.as_view(), name='serach'),
  ##############################   parties all views ########################################
              path('about/', views.AboutView.as_view(), name='about'),
              path('contact/', views.ContactView.as_view(), name='contact'),
              path('category/', views.CategoryView.as_view(), name='category'),
              path('listing/', views.ListingView.as_view(), name='listing'),
              path('success/', views.ContactSuccessView.as_view(), name="success"),
              path('filter-category/', views.FilterCategory.as_view(), name='filter_cate'),
              path('filter-category/<int:id>/', views.FilterCate.as_view(), name='cate_filter' ),
              path('filter-location/<str:loc>/', views.Filterlocation.as_view(), name='location_filter' ),
              path('filter-subcategory/<int:id>/', views.FilterSubcategory.as_view(), name='filter_subcategory' ),
              path('send/',views.SendQuery.as_view(), name='send'),
              path('subscribe/',views.subscribe ,name='subscribe')
  ##############################  end parties all views ######################################
]

pharma/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from CommonApp import views 
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    #error 404
    path('404',views.Error_404,name="404"),
    path('admin/', admin.site.urls,name="admin_dashboard"),
    path('account/',include('AccountApp.urls',namespace='AccountApp'),name='account_app'),
    path('common/',include('CommonApp.urls',namespace='CommonApp'),name='common_app'),
    path('franchise/',include('FranchiseApp.urls',namespace='FranchiseApp'),name='franchise_app'),
    path('',include('B2bApp.urls',namespace='B2bApp'),name='b2b_app'),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

B2bApp/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from B2bApp . models import *
# from tinymce.widgets import TinyMCE
from django.forms import MultiWidget, TextInput

class ContactForm(forms.Form):
    name=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': "form-control " }))
    email=forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'form-control'}))
    subject=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class': "form-control"}))
    message=forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows':4,'class': "form-control" }))
    # captcha = CaptchaField()
    

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        cl_data =super().clean()

        # Cleaned data
        cl_data = self.clean()
        name = cl_data.get('name').strip()
        from_email = cl_data.get('email')
        subject = cl_data.get('subject')
        
        msg = f'hi {name},'
        msg += f'\n"{from_email}"\n\n'
        msg += f'\n"{subject}"\n\n'
        msg += cl_data.get('message')

        return subject, msg
  

    def send(self):
        # send email using the self.cleaned_data dictionary
        
        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('email', 'name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Subscriber.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already subscribed.')
        return email

B2bApp/views.py
from django.shortcuts import render ,redirect
from B2bApp .models import *
from django.views import View
from B2bApp .forms import *
from CommonApp .models import *
from  AccountApp .models import *
from django.contrib import messages
from django.core.paginator import Paginator
from B2bApp  .forms import ContactForm,send_mail
from django.views.generic import FormView, TemplateView
from django.urls import reverse_lazy
from django.db.models import Q
from django.template.loader import get_template

# Create your views here.
# below import is done for sending emails

from django.conf import settings
from django.core.mail import message
from django.core.mail import send_mail,EmailMultiAlternatives
from django.core import mail
from django.core.mail.message import EmailMessage
##########################################
######### Home Function Start ############
##########################################   
class HomeView(View):
    def get(self, request):
     category=Category.objects.all()
     company=CompanyInfo.objects.all()
     locations=CompanyInfo.objects.all()
     product=Product.objects.all()
     unq_list=[]
     for i in locations:
       unq_list.append(i.Company_location)
     context={
       "category":Category.objects.all(),
       "location":set(unq_list),
        'product':product,
        "company":company,
        "logo":WebsiteLogo.objects.all(),
        "form":SubscriberForm(),
        "category":category
     }
     return render(request, 'b2b/index.html',context)
##########################################
######### Home Function End ##############
##########################################  

##########################################
######### About Function Start ###########
##########################################  
class AboutView(View):
    def get(self, request):
     context={
        "logo":WebsiteLogo.objects.all()
     }
     return render(request, 'b2b/about.html',context)
##########################################
######### About Function end #############
########################################## 
 
##########################################
######### Contact Function start #########
##########################################
class ContactView(FormView):
    template_name = 'b2b/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('B2bApp:success')
    def form_valid(self, form):
        # Calls the custom send method
        form.send()
        return super().form_valid(form)
    def get(self,request):
      context={
         "logo":WebsiteLogo.objects.all(),
          "form":ContactForm
      }
      return render(request,self.template_name,context)
##########################################
######### Contact Function End ###########
##########################################   
class ContactSuccessView(TemplateView):
    
    template_name = 'b2b/success.html'

##########################################
############# Category Function ##########
##########################################
class CategoryView(View):
    def get(self, request):
     product=Product.objects.all()
     
     context={
       'product':product,
        "logo":WebsiteLogo.objects.all()
     }
     return render(request, 'b2b/category.html',context)
##########################################
############# Category Function ##########
##########################################

##########################################
############# Listing Function ###########
##########################################
class ListingView(View):
 def get(self,request):
    products=CompanyInfo.objects.all()
    subCategorys=SubCategory.objects.all()
    all_page=CompanyInfo.objects.all()
    paginator=Paginator(all_page,7)
    page_no=request.GET.get('page')
    page_obj=paginator.get_page(page_no)
    locations=CompanyInfo.objects.all()
    unq_list=[]
    for i in locations:
       unq_list.append(i.Company_location)
       context={
         'products':products,
         'subCategorys':subCategorys,
         'page_obj':page_obj,
         "category":Category.objects.all(),
         "location":set(unq_list),
          "logo":WebsiteLogo.objects.all()
         }
    return render(request, 'b2b/listings.html',context)
##########################################
############# Listing Function ###########
##########################################

##########################################
######### Fliter cate Function start #####
##########################################
class FilterCategory(View):
  def get(self,request):
     cate_name_get=request.GET.get('cate')
     get_filter_id=Category.objects.filter(name=cate_name_get)[0]
     filterdata=CompanyInfo.objects.filter(Company_location=request.GET.get('loc'),Company_category=get_filter_id.id)
     subCategorys=SubCategory.objects.all()
     all_page=filterdata
     paginator=Paginator(all_page,7)
     page_no=request.GET.get('page')
     page_obj=paginator.get_page(page_no)
     data_filtered=[]
     for i in filterdata:
      if str(i.Company_category)==request.GET.get('cate'):
       data_filtered.append(i)
     locations=CompanyInfo.objects.all()
     unq_list=[]
     for i in locations:
      unq_list.append(i.Company_location)
     context={
      "page_obj":data_filtered,
       "category":Category.objects.all(),
      'subCategorys':subCategorys,
       "location":set(unq_list),
       "page_obj":page_obj,
        "logo":WebsiteLogo.objects.all()
     }
     return  render(request, 'b2b/listings.html',context)
  
##########################################
######### Fliter cate Function end #######
##########################################

##########################################
######### Fliter cate Function start #####
##########################################  
class FilterCate(View):
  def get(self,request,id):
     data=Category.objects.get(pk=id)
     filterdata=data.company.all()
     subCategorys=SubCategory.objects.all()
     all_page=filterdata
     paginator=Paginator(all_page,7)
     page_no=request.GET.get('page')
     page_obj=paginator.get_page(page_no)
     data_filtered=[]
     for i in filterdata:
      if str(i.Company_category)==request.GET.get('cate'):
       data_filtered.append(i)
     locations=CompanyInfo.objects.all()
     unq_list=[]
     for i in locations:
      unq_list.append(i.Company_location)
     context={
      "page_obj":data_filtered,
       "category":Category.objects.all(),
      'subCategorys':subCategorys,
       "location":set(unq_list),
       "page_obj":page_obj,
        "logo":WebsiteLogo.objects.all()
     }
     return  render(request, 'b2b/listings.html',context)
##########################################
######### Fliter cate Function end #######
##########################################    

##########################################
######### Fliter loc Function start ######
##########################################  
class Filterlocation(View):
    def get(self,request,loc):
     filterdata=CompanyInfo.objects.filter(Company_location=loc)
     locations=CompanyInfo.objects.all()
     subCategorys=SubCategory.objects.all()
     all_page=filterdata
     paginator=Paginator(all_page,7)
     page_no=request.GET.get('page')
     page_obj=paginator.get_page(page_no)
     unq_list=[]
     for i in locations:
       unq_list.append(i.Company_location)
          
     context={
        "page_obj":filterdata,
       "location":set(unq_list),
       'subCategorys':subCategorys,
        "page_obj":page_obj,
         "logo":WebsiteLogo.objects.all()

          }
     return  render(request, 'b2b/listings.html',context)
##########################################
######### Fliter loc Function end ########
##########################################  

##########################################
###### Fliter Subcate Function start #####
##########################################  
class FilterSubcategory(View):
    def get(self,request,id):
     data=Product.objects.get(pk=id)
     filterdata=data.company.all()
     locations=CompanyInfo.objects.all()
     subCategorys=SubCategory.objects.all()
     all_page=filterdata
     paginator=Paginator(all_page,7)
     page_no=request.GET.get('page')
     page_obj=paginator.get_page(page_no)
     unq_list=[]
     for i in locations:
       unq_list.append(i.Company_location)
          
     context={
        "page_obj":filterdata,
       "location":set(unq_list),
       'subCategorys':subCategorys,
        "page_obj":page_obj,
         "logo":WebsiteLogo.objects.all()
        }
     return  render(request, 'b2b/listings.html',context)
##########################################
######## Fliter Subcate Function end #####
##########################################    

##########################################
########## SendFunction start ###########
##########################################  
class SendQuery(View):
  def post(self,request):
   if request.method == 'POST':
     name=request.POST.get('name')
     email=request.POST.get('emailid')
     phone=request.POST.get('number')
     message=request.POST.get('mes')
     obj_query=SendPage.objects.create(name=name,email=email,phone=phone,message=message)
     obj_query.save()
     #emails sending starts from here
     from_email=settings.EMAIL_HOST_USER
     connection=mail.get_connection()
     connection.open()
     email_message=mail.EmailMessage(f'{email}',f'Name: {name}\nEmail : {email}\nPhone: {phone}\nQUERY : {message}',from_email,['pharmastar64@gmail.com','pharmastar64@gmail.com'],connection=connection)
     #   email_client=mail.EmailMessage('PharmaXpert Response','Thanks For Reaching us\n\nPharmaXpert.com\n\nofficialmitsmarketing@gmail.com',connection=connection)
     #   connection.send_messages([email_message,email_client])
     connection.send_messages([email_message])
     connection.close()
     #   messages.info(request,"Thanks For Reaching Us! We will get back you soon....")
     context={
        "logo":WebsiteLogo.objects.all()
     }

B2bApp/templates/b2b/about.html
{% extends 'core/core.html' %}
{% load static %}
{% block title %}About{% endblock title %}
{% block main-content %}
   <section class="about-section mt-4">
        <div class="container p-3">
            <div class="row">                
                <div class="content-column col-lg-6 col-md-12 col-sm-12 order-2">
                    <div class="inner-column">
                        <div class="sec-title">
                            <h2 class="title">About PharmaXpert</h2>
                            <!-- <h2>We are Creative Tech Enthusiast working since 2023</h2> -->
                        </div>
                        <div class="text">
                           Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque quae aperiam eos vel alias maiores tenetur laborum culpa repudiandae nostrum.</div>
                      <div class="text">
                       Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima consectetur, modi quidem molestias perspiciatis, animi voluptatem nobis autem, eum numquam commodi accusantium dignissimos deserunt hic porro voluptates reprehenderit voluptate dolore!
                      </div>
                       
                    </div>
                </div>

                <!-- Image Column -->
                <div class="image-column col-lg-6 col-md-12 col-sm-12">
                    <div class="inner-column wow fadeInLeft">
                      <div class="author-desc">
                        <h2>PharmaXpert</h2>
                        <span>B2B MARKET PLACE</span>
                      </div>
                        <figure class="image-1"><a href="#" class="lightbox-image" data-fancybox="images"><img title="Rahul Kumar Yadav" src="https://i.ibb.co/QP6Nmpf/image-1-about.jpg" alt=""></a></figure>
                     
                    </div>
                </div>
              
            </div>
         
        </div>
    </section>

   
 {% endblock main-content %}

B2bApp/templates/b2b/category.html
{% extends 'core/core.html' %}
{% load static %}
{% block title %}Category{% endblock title %}
{% block main-content %}
 
      <!-- Start Produts category -->
       <div class="container mt-5 p-5"   data-aos="fade-up" data-aos-duration="2000"  >
         <h1 class="text-center  text-white" style="background-color: black;">Product Category</h1>
         <div class="row mt-5 ">
         {% for pro in product %}
            <div class="col-xl-4 col-sm-6">
                      <a href="{% url 'B2bApp:filter_subcategory' pro.id %}" class="wsus__category_single">
                      <div class="wsus__category_img">
                          <img src="{{pro.Product_image.url}}" alt="img" class="img-fluid w-100">
                          </div>
                          <div class="wsus__category_text">
                              <div class="wsus__category_text_center">
                                <p >{{pro.Product_category}}</p>
                           </div>
                          </div>
                      </a>
                  </div>
                  {% endfor %} 
            {% comment %} {% for pro in product %}
            <div class="col-lg-3" >
              <div class="card  mt-4" >
                <div id="cat" >
              <img src="{{pro.Product_image.url}}" alt="" class="w-100 " style="opacity: 0.3; ">
            </div>
              <div class="centered ">
              <h6 class="text-white ">{{pro.Product_category}}</h6>
             <a href="{% url 'B2bApp:filter_subcategory' pro.id %}" class=" btn btn-outline-warning"> view listings</a></div>
            </div>
          </div>
          {% endfor %}   {% endcomment %}
          </div>
          </div>
          </div>
  
        <!-- End Produts category -->
  
  {% endblock main-content %}

B2bApp/templates/b2b/contact.html
{% extends 'core/core.html' %}
{% load static %}
{% block title %}Contact{% endblock title %}
{% block main-content %} 


  <!-- Contact Start -->
  <div class="container-fluid w-75 mb-5" style="background: linear-gradient(to right, #1488cc, #2b32b2); border-radius: 2%; margin-top:10%;" data-aos="flip-up" data-aos-duration="2000"  >
      <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4 text-center mt-1"><span class=" pr-3 text-white">Contact Us</span></h2>
      <div class="row px-xl-5">
          <div class="col-lg-5 mb-5">
              <div class="contact-form  p-30" >
                  <div id="success"></div>
                  <form name="sentMessage" id="contactForm" navigation method="post">
                    {% csrf_token %}
                 <!-- {{form.as_p}} -->
                 <p class="m-0 text-white" style="color: azure;">{{ form.label_tag }}</p> 
                 {{form}}
                    <div>
                    <button class="btn btn-danger py-2 px-4 mt-2" type="submit" id="sendMessageButton" style="background: linear-gradient(to right, #ff334e, #f30808, #f52804);">Send Message</button>
                    </div>
                   </form>
                  {% if messages %}
                  {% for message in messages %}
                  <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
                  {% endfor %}
                 {% endif %}
        </div>
          </div>
          <div class="col-lg-7 mb-5">
              <div class=" p-30 mb-30" >
                  <iframe style="width: 100%; height: 250px;border-radius: 2%;"
                  src="https://maps.google.com/maps?q=panchkula&t=&z=14&ie=UTF8&iwloc=&output=embed"
                  frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
              </div>
              <div class=" p-30 mb-3 mt-2  text-center" style="    background: linear-gradient(to right, #232526, #414345); border-radius: 2%; ">
                  <p class="mb-2 text-white ml-3"><i class="fa fa-map-marker-alt text-white mr-3"></i>Punchkula</p>
                  <p class="mb-2 text-white ml-3"><i class="fa fa-envelope text-white mr-3"></i>pharmaxpert.com</p>
                  <p class="mb-2 text-white ml-3"><i class="fa fa-phone-alt text-white mr-3"></i>+000 333 5555</p>
              </div>
          </div>
      </div>
  </div> 
  
 {% endblock main-content %}

B2bApp/templates/b2b/success.html
{% extends 'core/core.html' %}
{% load static %}
{% block title %}Success{% endblock title %}
{% block main-content %}

<div class="" >
<div class="mx-auto my-4 text-center" >
    <h1 class="fw-bolder text-success">We sent your message</h1>
    <h3 class="fw-bolder text-success">Thanks For Reaching Us! We will get back you soon....</h3>
    <div ><iframe src="https://giphy.com/embed/tf9jjMcO77YzV4YPwE" width="200" height="200"  frameborder="0"  frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
    {% comment %} <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200"  frameborder="0" class="giphy-embed bg-success" allowFullScreen></iframe></div> {% endcomment %}
    {% comment %} <p class="my-5">You can send another in the <a href="{% url 'B2bApp:home' %}">Home page</a></p> {% endcomment %}
</div>
</div>
{% endblock main-content %}