B2bApp/urls.py
from django.urls import path
from B2bApp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name= 'B2bApp'
urlpatterns = [
              path('', views.HomeView.as_view(), name='home'),
              path('serach/', views.Serach.as_view(), name='serach'),
  ##############################   parties all views ########################################
              path('about/', views.AboutView.as_view(), name='about'),
              path('contact/', views.ContactView.as_view(), name='contact'),
              path('category/', views.CategoryView.as_view(), name='category'),
              path('listing/', views.ListingView.as_view(), name='listing'),
              path('success/', views.ContactSuccessView.as_view(), name="success"),
              path('filter-category/', views.FilterCategory.as_view(), name='filter_cate'),
              path('filter-category/<int:id>/', views.FilterCate.as_view(), name='cate_filter' ),
              path('filter-location/<str:loc>/', views.Filterlocation.as_view(), name='location_filter' ),
              path('filter-subcategory/<int:id>/', views.FilterSubcategory.as_view(), name='filter_subcategory' ),
              path('send/',views.SendQuery.as_view(), name='send'),
              path('subscribe/',views.subscribe ,name='subscribe')
  ##############################  end parties all views ######################################
]

FranchiseApp/urls.py
from django.urls import path
from FranchiseApp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name= 'FranchiseApp'
urlpatterns = [
       #mits-healthacre url
       path('franchise/home/<int:pk>', views.HomeView.as_view(), name='home'),
       path('franchise/about/<int:pk>', views.AboutView.as_view(), name='about'),
       path('franchise/our_range/<int:pk>', views.OurRangeView.as_view(), name='Our_range'),
       path('franchise/contact/<int:pk>', views.ContactView.as_view(), name='Contact'),
       path('franchise/products/<int:pk>', views.ProductView.as_view(), name='Products'),
       path('franchise/product_detail/<int:pk>', views.ProductDetailView.as_view(), name='Productdetail'),
       path('send/',views.SendQuery.as_view(), name='send'),
     

]

pharma/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from CommonApp import views 
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    #error 404
    path('404',views.Error_404,name="404"),
    path('admin/', admin.site.urls,name="admin_dashboard"),
    path('account/',include('AccountApp.urls',namespace='AccountApp'),name='account_app'),
    path('common/',include('CommonApp.urls',namespace='CommonApp'),name='common_app'),
    path('franchise/',include('FranchiseApp.urls',namespace='FranchiseApp'),name='franchise_app'),
    path('',include('B2bApp.urls',namespace='B2bApp'),name='b2b_app'),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FranchiseApp/models.py
from django.db import models
from django.utils.safestring import mark_safe
from autoslug import AutoSlugField
from B2bApp .models import *
# Create your models here.


    
class Send(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(unique=False)
    phone=models.CharField(max_length=14)
    message=models.TextField(max_length=500)

    def __str__(self):
        return self.name
    
class MitsProducts(models.Model):
    company=models.ForeignKey(CompanyInfo,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
    pro_image=models.ImageField(upload_to="mitsproductimage")
    description=models.TextField(max_length=500)
    packing=models.CharField(max_length=100)
    tags=models.CharField(max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        ordering=['name']
    
    
    def delete(self,*args, **kwargs):
        self.pro_image.delete()
        return super(MitsProducts, self).delete(*args, **kwargs)

    def pro_images(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
    pro_images.short_description ='pro_image'
    pro_images.allow_tag =True

# class ShineProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="shineproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
    
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']
#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(ShineProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class EdmundProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="edmundproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
   

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(EdmundProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

    
# class MedFenseProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="medfensseproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
  
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(MedFenseProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class RapidProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="rapidproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
 
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(RapidProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class ServoProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="servoproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(ServoProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class RonishProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="ronishproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(RonishProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

FranchiseApp/views.py
from django.shortcuts import render,redirect
from django.views import View
from FranchiseApp .models import *
from CommonApp .models import *
from B2bApp.models import *
import random
from django.db.models import Count
# below import is done for sending emails
from django.conf import settings
from django.core.mail import message
from django.core.mail import send_mail
from django.core import mail
from django.core.mail.message import EmailMessage
# Create your views here. 
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
# from django.utils.encoding import force_bytes
# from django.utils.http import urlsafe_base64_encode
import uuid

##########################################
########## mitshealthcare views ##########
##########################################
class HomeView(View):
    def get(self,request,pk):
    #  pk=str(uuid.uuid4())
     comp=CompanyInfo.objects.get(pk = pk)
     product=MitsProducts.objects.filter(company_id=pk)
     company=CompanyInfo.objects.get(pk = pk)
     print(company)
     banner=Franchise_company_banner.objects.filter(company_id=pk)
     business=Company_Additional_Business.objects.filter(company_id=pk)
     context={
        "product":product,
        'company':company,
        "banner":banner,
        'business': business,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
     return render(request,'mitsheathcare/index.html',context)
    
class AboutView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        company=CompanyInfo.objects.get( pk =pk)
        business=Company_Additional_Business.objects.all()[0:5]
        context={
            'company':company,
            'business': business,
              "logo":WebsiteLogo.objects.all(),
              "comp":comp
        }
        return render(request,'mitsheathcare/about.html',context)

class OurRangeView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        product=MitsProducts.objects.filter(company_id=pk)
        company=CompanyInfo.objects.get(pk=pk)
        context={
        "product":product,
        'company':company,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
        return render(request,'mitsheathcare/our_range.html',context)

class ContactView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        company=CompanyInfo.objects.get(pk=pk)
        context={
            'company':company,
            "logo":WebsiteLogo.objects.all(),
            "comp":comp
        }
        return render(request,'mitsheathcare/contact.html',context)

class ProductView(View):
    def get(self,request,pk):
         comp=CompanyInfo.objects.get(pk = pk)
         total_issues = MitsProducts.objects.all().filter(company_id=pk).count()
         product=MitsProducts.objects.filter(company_id=pk)
         company=CompanyInfo.objects.get(pk=pk)
        #  comp=MitsProducts.objects.get(pk=pk)
         context={
        "product":product,
         'total_issues': total_issues, 
        #  'comp':comp,
        'company':company,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
         return render(request,'mitsheathcare/products.html',context)
    
class ProductDetailView(View):
    def get(self,request,pk):
        # comp=CompanyInfo.objects.get(pk=pk)
        detail=MitsProducts.objects.get(pk=pk)
        products = MitsProducts.objects.all().order_by('tags')[:60]
        related = random.sample(list(products) , 4)
        context={
         'detail':detail,
         'related':related,
         'company':detail.company,
         "logo":WebsiteLogo.objects.all(),
          "comp":detail.company
         }
        return render(request,'mitsheathcare/product_detail.html',context)

class SendQuery(View):
  def post(self,request):
   if request.method == 'POST':
     name=request.POST.get('naam')
     email=request.POST.get('mail')
     phone=request.POST.get('no')
     message=request.POST.get('dec')
     query=Send.objects.create( name=name,email=email,phone=phone,message=message)
     query.save()
    #emails sending starts from here
     from_email=settings.EMAIL_HOST_USER
     connection=mail.get_connection()
     connection.open()
     email_message=mail.EmailMessage(f'{email}',f'Name: {name}\nEmail : {email}\nPhone: {phone}\nQUERY : {message}',from_email,['pharmastar64@gmail.com','pharmastar64@gmail.com'],connection=connection)
     #email_client=mail.EmailMessage('PharmaXpert Response','Thanks For Reaching us\n\nPharmaXpert.com\n\nofficialmitsmarketing@gmail.com',connection=connection)
  
     connection.send_messages([email_message])
     connection.close()
     #   messages.info(request,"Thanks For Reaching Us! We will get back you soon....")
     return redirect('B2bApp:success')
   context={
        "logo":WebsiteLogo.objects.all(),
   }
   return render (request,'b2b/success.html',context)
  

FranchiseApp/templates/mitsheathcare/mitscore/core.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>PharmaXpert Vendor  {% block title %}{{title}}{% endblock title %}</title>
     <!-- css links start -->
     {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> {% endcomment %}
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
     {% comment %} <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
     <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/> 
     <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet"/> {% endcomment %}
     {% comment %} <link href="https://cdn.datatables.net/v/bs4-4.6.0/jszip-2.5.0/dt-1.13.4/b-2.3.6/b-html5-2.3.6/b-print-2.3.6/datatables.min.css" rel="stylesheet"/>   {% endcomment %}
     <link rel="stylesheet" href="{% static 'care/vendor/slick/slick.css' %}">
     <link rel="stylesheet" href="{% static 'care/vendor/datatables/datatable.min.css' %}">
     <link rel="stylesheet" href="{% static 'care/vendor/slick/slick-theme.css' %}">
     <link rel="stylesheet" href="{% static 'care/vendor/bootstrap/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'care/css/style.css' %}">
     <link rel="stylesheet" href="{% static 'care/css/responsive.css' %}">
     <!-- css links  -->

</head>
<body>
  <!-- navbar start   -->
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color:{{comp.Company_color1}};">
    <a class="navbar-brand" href="{% url 'FranchiseApp:home' company.id %}"><img src="{{company.Company_logo.url}}" alt="" style="width: 150px;"></a>
   <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-left" id="navbarSupportedContent">
    <ul class="navbar-nav ">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'FranchiseApp:home' company.id %}" style="color:{{comp.Company_color2}};">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'FranchiseApp:about' company.id %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'FranchiseApp:Our_range' company.id  %}">Our Range</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'FranchiseApp:Products' company.id  %}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'FranchiseApp:Contact' company.id  %}">Contact Us</a>
      </li>
      <a class="btn ml-5 text-white" href="{{company.Company_brochure.url}}" role="button" style="background-color:{{comp.Company_color2}};"><i class="fa-sharp fa-regular fa-file-pdf"></i> Download Brochure</a>
    </ul>
  </div>
</nav>

<!-- navbar end  -->


 {% block main-content %}{% endblock main-content %}

<!--- footer start--->
<!-- Footer -->

<footer class="page-footer font-small  text-white mt-5" style="background-color: {{comp.Company_color2}}; ">


<!-- Footer Links -->
<div class="container text-center text-md-left">
<!-- Grid row -->
<div class="row">
<!-- Grid column -->
<div class="col-md-3 mx-auto">
<!-- Links -->
<h5 class="font-weight-bold text-uppercase mt-3 mb-4">Member of</h5>
<ul class="list-unstyled">
{% for l in logo %}
  <li><a href="#!"><img src="{{l.logo_image.url}}" alt="" class="w-75"></a></li>
{% endfor %}

</ul>
</div>
<!-- Grid column -->
<hr class="clearfix w-100 d-md-none">
<!-- Grid column -->
<div class="col-md-3 mx-auto">
<!-- Links -->
<h5 class="font-weight-bold text-uppercase mt-3 mb-4">Sitemap</h5>

        <ul class="list-unstyled">
          <li>
            <a href="{% url 'FranchiseApp:home' company.id %}" class="text-white">Home</a>
          </li>
          <li>
            <a href="{% url 'FranchiseApp:about' company.id %}" class="text-white">About us</a>
          </li>
          <li>
            <a href="{% url 'FranchiseApp:Our_range'  company.id %} " class="text-white">Our Range</a>
          </li>
          <li>
            <a href="{% url 'FranchiseApp:Products'  company.id %}" class="text-white">Products</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4" >Contact</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-white">{{company.Company_registed_address}}</a>
          </li>
        </ul>
        </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Downloads</h5>

        <ul class="list-unstyled">
          <li>
            <a href="{% url 'FranchiseApp:Products' company.id %}"class="text-white">Product List</a>
          </li>
          <li>
         <a href="{{company.Company_brochure.url}}"class="text-white">Brochure</a>
      </li>
      </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2023 Copyright:
    <a href="/" class="text-white"> PharmaXpert.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
<!---- footer end---->


                                    
<!-- javascripts links Start  -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'care/js/jquery-3.6.0.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<script src="{% static 'care/js/slick.min.js' %}"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="{% static 'care/vendor/datatables/datatable.js' %}"></script>
<script src="{% static 'care/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
<script src="{% static 'care/js/scripts.js' %}"></script>
<!-- javascripts links End  -->
<script>

$(document).ready(function(){
var table = $('#myTable').DataTable();
new $.fn.dataTable.Buttons( table, {
    buttons: [
        'copy', 'excel', 'pdf','print'
    ]
} );
 
table.buttons().container()
    .appendTo( $('tr th.heading', table.table().container() ) );
});

</script>
</body>
</html>