B2bApp/urls.py
from django.urls import path
from B2bApp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name= 'B2bApp'
urlpatterns = [
              path('', views.HomeView.as_view(), name='home'),
              path('serach/', views.Serach.as_view(), name='serach'),
  ##############################   parties all views ########################################
              path('about/', views.AboutView.as_view(), name='about'),
              path('contact/', views.ContactView.as_view(), name='contact'),
              path('category/', views.CategoryView.as_view(), name='category'),
              path('listing/', views.ListingView.as_view(), name='listing'),
              path('success/', views.ContactSuccessView.as_view(), name="success"),
              path('filter-category/', views.FilterCategory.as_view(), name='filter_cate'),
              path('filter-category/<int:id>/', views.FilterCate.as_view(), name='cate_filter' ),
              path('filter-location/<str:loc>/', views.Filterlocation.as_view(), name='location_filter' ),
              path('filter-subcategory/<int:id>/', views.FilterSubcategory.as_view(), name='filter_subcategory' ),
              path('send/',views.SendQuery.as_view(), name='send'),
              path('subscribe/',views.subscribe ,name='subscribe')
  ##############################  end parties all views ######################################
]

FranchiseApp/urls.py
from django.urls import path
from FranchiseApp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name= 'FranchiseApp'
urlpatterns = [
       #mits-healthacre url
       path('franchise/home/<int:pk>', views.HomeView.as_view(), name='home'),
       path('franchise/about/<int:pk>', views.AboutView.as_view(), name='about'),
       path('franchise/our_range/<int:pk>', views.OurRangeView.as_view(), name='Our_range'),
       path('franchise/contact/<int:pk>', views.ContactView.as_view(), name='Contact'),
       path('franchise/products/<int:pk>', views.ProductView.as_view(), name='Products'),
       path('franchise/product_detail/<int:pk>', views.ProductDetailView.as_view(), name='Productdetail'),
       path('send/',views.SendQuery.as_view(), name='send'),
     

]

pharma/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from CommonApp import views 
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    #error 404
    path('404',views.Error_404,name="404"),
    path('admin/', admin.site.urls,name="admin_dashboard"),
    path('account/',include('AccountApp.urls',namespace='AccountApp'),name='account_app'),
    path('common/',include('CommonApp.urls',namespace='CommonApp'),name='common_app'),
    path('franchise/',include('FranchiseApp.urls',namespace='FranchiseApp'),name='franchise_app'),
    path('',include('B2bApp.urls',namespace='B2bApp'),name='b2b_app'),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FranchiseApp/models.py
from django.db import models
from django.utils.safestring import mark_safe
from autoslug import AutoSlugField
from B2bApp .models import *
# Create your models here.


    
class Send(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(unique=False)
    phone=models.CharField(max_length=14)
    message=models.TextField(max_length=500)

    def __str__(self):
        return self.name
    
class MitsProducts(models.Model):
    company=models.ForeignKey(CompanyInfo,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
    pro_image=models.ImageField(upload_to="mitsproductimage")
    description=models.TextField(max_length=500)
    packing=models.CharField(max_length=100)
    tags=models.CharField(max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        ordering=['name']
    
    
    def delete(self,*args, **kwargs):
        self.pro_image.delete()
        return super(MitsProducts, self).delete(*args, **kwargs)

    def pro_images(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
    pro_images.short_description ='pro_image'
    pro_images.allow_tag =True

# class ShineProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="shineproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
    
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']
#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(ShineProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class EdmundProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="edmundproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
   

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(EdmundProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

    
# class MedFenseProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="medfensseproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
  
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(MedFenseProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class RapidProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="rapidproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)
 
#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(RapidProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class ServoProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="servoproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(ServoProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

# class RonishProducts(models.Model):
#     name=models.CharField(max_length=100)
#     slug = AutoSlugField(populate_from='name',unique=True, null=True, default=None)
#     pro_image=models.ImageField(upload_to="ronishproductimage")
#     description=models.TextField(max_length=500)
#     packing=models.CharField(max_length=100)
#     tags=models.CharField(max_length=100)

#     def __str__(self):
#         return self.name
#     class Meta:
#         ordering=['name']

#     def delete(self,*args, **kwargs):
#         self.pro_image.delete()
#         return super(RonishProducts, self).delete(*args, **kwargs)

#     def pro_images(self):
#         return mark_safe('<img src="{}" width="100" />'.format(self.pro_image.url))
#     pro_images.short_description ='pro_image'
#     pro_images.allow_tag =True

FranchiseApp/views.py
from django.shortcuts import render,redirect
from django.views import View
from FranchiseApp .models import *
from CommonApp .models import *
from B2bApp.models import *
import random
from django.db.models import Count
# below import is done for sending emails
from django.conf import settings
from django.core.mail import message
from django.core.mail import send_mail
from django.core import mail
from django.core.mail.message import EmailMessage
# Create your views here. 
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
# from django.utils.encoding import force_bytes
# from django.utils.http import urlsafe_base64_encode
import uuid

##########################################
########## mitshealthcare views ##########
##########################################
class HomeView(View):
    def get(self,request,pk):
    #  pk=str(uuid.uuid4())
     comp=CompanyInfo.objects.get(pk = pk)
     product=MitsProducts.objects.filter(company_id=pk)
     company=CompanyInfo.objects.get(pk = pk)
     print(company)
     banner=Franchise_company_banner.objects.filter(company_id=pk)
     business=Company_Additional_Business.objects.filter(company_id=pk)
     context={
        "product":product,
        'company':company,
        "banner":banner,
        'business': business,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
     return render(request,'mitsheathcare/index.html',context)
    
class AboutView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        company=CompanyInfo.objects.get( pk =pk)
        business=Company_Additional_Business.objects.all()[0:5]
        context={
            'company':company,
            'business': business,
              "logo":WebsiteLogo.objects.all(),
              "comp":comp
        }
        return render(request,'mitsheathcare/about.html',context)

class OurRangeView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        product=MitsProducts.objects.filter(company_id=pk)
        company=CompanyInfo.objects.get(pk=pk)
        context={
        "product":product,
        'company':company,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
        return render(request,'mitsheathcare/our_range.html',context)

class ContactView(View):
    def get(self,request,pk):
        comp=CompanyInfo.objects.get(pk = pk)
        company=CompanyInfo.objects.get(pk=pk)
        context={
            'company':company,
            "logo":WebsiteLogo.objects.all(),
            "comp":comp
        }
        return render(request,'mitsheathcare/contact.html',context)

class ProductView(View):
    def get(self,request,pk):
         comp=CompanyInfo.objects.get(pk = pk)
         total_issues = MitsProducts.objects.all().filter(company_id=pk).count()
         product=MitsProducts.objects.filter(company_id=pk)
         company=CompanyInfo.objects.get(pk=pk)
        #  comp=MitsProducts.objects.get(pk=pk)
         context={
        "product":product,
         'total_issues': total_issues, 
        #  'comp':comp,
        'company':company,
        "logo":WebsiteLogo.objects.all(),
        "comp":comp
        }
         return render(request,'mitsheathcare/products.html',context)
    
class ProductDetailView(View):
    def get(self,request,pk):
        # comp=CompanyInfo.objects.get(pk=pk)
        detail=MitsProducts.objects.get(pk=pk)
        products = MitsProducts.objects.all().order_by('tags')[:60]
        related = random.sample(list(products) , 4)
        context={
         'detail':detail,
         'related':related,
         'company':detail.company,
         "logo":WebsiteLogo.objects.all(),
          "comp":detail.company
         }
        return render(request,'mitsheathcare/product_detail.html',context)

class SendQuery(View):
  def post(self,request):
   if request.method == 'POST':
     name=request.POST.get('naam')
     email=request.POST.get('mail')
     phone=request.POST.get('no')
     message=request.POST.get('dec')
     query=Send.objects.create( name=name,email=email,phone=phone,message=message)
     query.save()
    #emails sending starts from here
     from_email=settings.EMAIL_HOST_USER
     connection=mail.get_connection()
     connection.open()
     email_message=mail.EmailMessage(f'{email}',f'Name: {name}\nEmail : {email}\nPhone: {phone}\nQUERY : {message}',from_email,['pharmastar64@gmail.com','pharmastar64@gmail.com'],connection=connection)
     #email_client=mail.EmailMessage('PharmaXpert Response','Thanks For Reaching us\n\nPharmaXpert.com\n\nofficialmitsmarketing@gmail.com',connection=connection)
  
     connection.send_messages([email_message])
     connection.close()
     #   messages.info(request,"Thanks For Reaching Us! We will get back you soon....")
     return redirect('B2bApp:success')
   context={
        "logo":WebsiteLogo.objects.all(),
   }
   return render (request,'b2b/success.html',context)
  

FranchiseApp/templates/mitsheathcare/contact.html
{% extends 'mitsheathcare/mitscore/core.html' %}
{% load static %}
{% block title %}Contact{% endblock title %}
{% block main-content %}

<section class="about"  id="abot" style="background-color: rgb(221, 221, 221);">
    <div class="about-intro content_above ">
        <div class="container ">
            <div class="row  company-header p-5  ">
              <div class="col-lg-7 col-md-6">
                <h4 class="mt-5">Contact us</h4>
        
                 <h4 class="mt-5">
                   {{company.Company_name}}<br><br>
                    
                   {{company.Company_registed_address}}<br><br>
                    
                  {{company.Company_ceo}}
                </h4>  
             
                    
                     
                  </div>
                  <div class="col-lg-5 col-md-6 p-4">
                    <div class="card " style="width: 100%;height: 100%;border-radius: 20px;">
                      <form action="{% url 'FranchiseApp:send' %}" method="post">
                  {% csrf_token %}
                    <div class="col-12  text-center text-white" style="border-radius: 20px; height: 40px;background:{{comp.Company_color2}}">
                      <h4>Send Query</h4>
                    </div>
                    <div class="row p-4">
                     
                      <div class="col-12 mt-2">
                        <input type="text" class="form-control" placeholder="Full name*" name="naam" required>
                      </div>
                      <div class="col-6 mt-4">
                        <input type="text" class="form-control" placeholder="E-mail*" name="mail" required>
                      </div>
                      <div class="col-6 mt-4">
                        <input type="text" class="form-control" placeholder="Phone*" name="no" required>
                      </div>
                       
                      <div class="col-12 mt-4">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter Your Message*" name="dec" required></textarea>
                      </div>
                      <div class="col-12 mt-4">
                      <button type="submit" class="btn  w-100  text-white" style="background:{{comp.Company_color2}};">Send</button>
                    </div>
                    </div>
                  </form>
                    </div>
                  </div>
                </div>
              </div>
             </div>
       </section>
    

{% endblock main-content %}

FranchiseApp/templates/mitsheathcare/index.html
{% extends 'mitsheathcare/mitscore/core.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block main-content %}

<section class="about "  id="abot" style="background-color: #ffffff;">
<div class="about-intro content_above ">
    <div class="container-fluid ">
        <div class="row  company-header p-5  ">
       
          <div class="col-lg-8 col-md-12">
           <div class="autoplay4 m-0 p-0" id=""data-slick='{"slidesToShow": 6, "settings":{"slidesToShow":4 }]}'>
           {% for i in banner %} 
            <div class="card bg-white m-0 p-0 " style="height: 100%; ">
            <img src="{{i.banner.url}}" alt=""  class=" w-100">
          </div>
           {% endfor %} 
             </div>
              </div>
             
              <div class="col-lg-4 col-md-6 p-4 mx-auto">
                <div class="card " style="width: 100%; border-radius: 20px;">
                  <form action="{% url 'FranchiseApp:send' %}" method="post">
                  {% csrf_token %}
                    <div class="col-12  text-center text-white" style="border-radius: 20px; height: 40px;background:{{comp.Company_color2}};">
                      <h4>Send Query</h4>
                    </div>
                    <div class="row p-4">
                     
                      <div class="col-12 mt-2">
                        <input type="text" class="form-control" placeholder="Full name*" name="naam" required>
                      </div>
                      <div class="col-6 mt-4">
                        <input type="text" class="form-control" placeholder="E-mail*" name="mail" required>
                      </div>
                      <div class="col-6 mt-4">
                        <input type="text" class="form-control" placeholder="Phone*" name="no" required>
                      </div>
                       
                      <div class="col-12 mt-4">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter Your Message*" name="dec" required></textarea>
                      </div>
                      <div class="col-12 mt-4">
                      <button type="submit" class="btn  w-100 text-white" style="background:{{comp.Company_color2}};">Send</button>
                    </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
         </div>
   </section>
   <h3 class="mt-3 text-center">Our Product Range</h3>
   <section style="background-color: rgb(233, 233, 235);" class="mt-3">
    
    <div class="autoplay p-3" id="" data-slick='{"slidesToShow": 6, "settings":{"slidesToShow":4 }]}'>
       {% for i in  product %}
    <a href="{% url 'FranchiseApp:Productdetail' i.id %}">
      <div class="card bg-white p-4 d-flex" style="height: 200px;"  >
          <img src="{{i.pro_image.url}}" height="150px" >
      </div>
    </a>
      {% endfor %}
    </div>
 
   </section>
   
<section id="about" class="about-contents section-padding mt-5">
    <div class="container">
        <div class="row">
            
<div class="col-lg-12 contents-wrapper">
    <div class="contents">
      <div class="row">
      <div class="col-lg-12 col-sm-6 mt-5 mt-md-0">
               
              {% comment %} {% for c in company  %} {% endcomment %}
                <h1>About {{ company.Company_name}}</h1>
                <p><b>{{ company.Company_name}}</b>
               {{ company.Company_about |striptags }}
                     <br><i></i></p> 
                <div class="table-responsive" style="margin-top:25px;">          
                      <table class="table table-condensed">
                          <tbody>
                            <tr>
                                <td><strong>Nature of Business</strong></td>
                                <td>{{ company.Company_nature_of_business}}</td>                                    
                              </tr>
                             <tr>
                                <td><strong>Additional Business</strong></td>
                                <td><ul>
                                  {% for i in  business %}
                                <li class="ml-4">{{i.name}}</li>
                                  {% endfor %}
                                </ul></td>                                    
                              </tr>
                              <tr>
                                <td><strong>Company CEO</strong></td>
                                <td>{{company.Company_ceo}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Corporate Office Address</strong></td>
                                <td>{{company.Company_corporate_address}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Registered Office Address</strong></td>
                                <td>{{company.Company_registed_address}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Industry</strong></td>
                                <td>{{company.Company_industry}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Total Number of Employees</strong></td>
                                <td>{{company.Company_total_employee}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Legal Status of Firm</strong></td>
                                <td>{{company.Company_legal_status_of_firm}}</td>                                    
                              </tr>
                              <tr>
                                <td><strong>Statutory Profile<br>PAN No</strong></td>
                                <td>{{company.Company_pan_no}}</td>                                    
                              </tr>
                               <tr>
                                <td><strong>GST No</strong></td>
                                <td>{{company.Company_gts_no}}</td>                                    
                              </tr>
                              <tr>
                        {% comment %} {% endfor %} {% endcomment %}
                    </ul>
                    </td>
                    </tr>
                    </tbody>
                    </table>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
 
  </section>
        
{% endblock main-content %}

<div class="slider-slide" aria-label="slide 5 of 15" role="group" style="box-sizing: border-box; display: inline-block; height: 19px; left: 760px; list-style-type: none; margin: auto 8px; position: absolute; top: 0px; transform: scale(1); transition: transform 0.4s linear 0s; vertical-align: top; width: 174px;" inert="" aria-hidden="true"><a href="https://company.pharmahopers.com/aelida-healthcare/product/aelfix-cv" target="_blank" aria-hidden="true" tabindex="-1"><img class="Carousel__Image-sc-bwtv6d-1 hWhvhm" src="https://www.pharmahopers.com/assets/images/products/6f7bbafd-fce3-4f8b-a63d-f41b5f31d96b-aelfix cv.png" alt="aelfix-cv"></a></div>

FranchiseApp/templates/mitsheathcare/product_detail.html
{% extends 'mitsheathcare/mitscore/core.html' %}
{% load static %}
{% block title %}Products_detail{% endblock title %}
{% block main-content %}
<section class="mt-5 ">
    <div class="site-section bg-white">
        <div class="container bg-white">
          <div>
            <ol style="display: flex;">
              <li style="list-style: none;">
                <a href="{% url 'FranchiseApp:home' company.id %}" style="font-size: 1rem;text-decoration: none;">Home</a>
                <i class="fa-solid fa-chevron-up fa-rotate-90 ml-3"style="color: #050505;"></i>
              </li>
              <li style="list-style: none;">
                <a href="{% url 'FranchiseApp:Products' company.id %}" style="font-size: 1rem;text-decoration: none;" class="ml-2">Products</a>
                <i class="fa-solid fa-chevron-up fa-rotate-90 ml-3"style="color: #050505;"></i>
              </li>
              <li style="list-style: none;">
                <a href="" style="font-size: 1rem;text-decoration: none;color: #050505;" class="ml-3">{{detail.name}}</a>
              
              </li>
            </ol>
          </div>
          <div class="row mt-5">
          
         <div class="col-lg-5 col-md-6 col-sm-6 col-xs-12 df">
          <div class="companyname" style="text-align: center !important;background: #fff;color: #000;">
            {{detail.name}}</div>
          <div class="zoom_imgb" style="max-height:390px;width: 100%;float: left;"><a style="float:left;width:100%;" title="Send Enquiry for St Kuff " href="" data-toggle="modal" data-target=".enquirybbbb1892">
            <img style="min-height:390px; max-height:390px;width: 100%;float: left;" src="{{detail.pro_image.url}}" alt="St Kuff"></a></div>
          <div class="companyname" style="text-align: center !important;background: #fff;color: #000;">
               </div>
      </div>
            <!-- <div class="col-md-4 mr-auto">
              <div class="card text-center  "  style="box-shadow: 0 25px 50px -12px #00000080;">
                <img src="{{edmund.pro_image.url}}" alt="Image" class="img-fluid p-4 ">
              </div>
            </div> -->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ml-5">
              <a class="companyinfo" href="{% url 'FranchiseApp:home' company.id %}">Mits Healthcare Pvt Ltd</a>
              <span class="inlinspanaddress">SCF - 416, Ist & 2nd Floor Motor Market Manimajra Chandigarh - 160101 , India</span>                     
              <table class="table">
              <!-- <caption style="font-weight: 700;color: #000;">Product Details:</caption> -->
              <thead>
                <th>Product Details:</th>
              </thead>
              <tbody>
                  <tr>
                      <td scope="row" width="40%">Product Name:</td>
                      <td>{{detail.name}}</td>
                  </tr> <tr>
                      <td scope="row" width="40%">Brand Name:</td>
                      <td>Mits Healthcare</td>
                  </tr> <tr>
                      <td scope="row" width="40%">Tags</td>
                      <td>{{detail.tags}}</td>
                  </tr>  <tr>
                      <td scope="row" width="40%">Packaging:</td>
                      <td>{{detail.packing}}</td>
                  </tr>  <tr>
                      <td scope="row" width="40%" style="line-height:18px !important;">Composition / Material Type:</td>
                      <td style="line-height:18px !important;">{{detail.description}}</td>
                  </tr>  
                </tbody>
          </table>
        </div>
  </div>
</div>

            <!-- <div class="col-md-5">
              <h2 class="text-black text-capitalize">{{edmund.name}}</h2>
              <p style="color:#8b8787;" class="mt-5 h5" >Description</p>
              <p class="h5">{{edmund.description}}</p>
              <p style="color:#8b8787;" class="mt-5 h5" >Tags</p>
              <p class="bg-dark  text-white text-center w-50 h5" >{{edmund.tags}}</p>
              <p style="color:#8b8787;" class="mt-5 h5" >Packing</p>
              <p class="h5">{{edmund.packing}}</p>
           </div> -->
          </div>
        </div>
      </div>
      <div class="container bg-white mt-5">
        <p class="Text-sc-uzvrb9-0 hrRunO">Related Products</p>
      <div class="row">
      
        {% for r in related %}
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
        <div class="sc-1kbxmi-0-FlexContainer-cnOyeg dXdIfy" direction="row" wrap="wrap">
          <a class="Anchor-sc-1nd3rwi-0 jIVSAC" href="{% url 'FranchiseApp:Productdetail' r.id %}">
            
            <img class="Product__Img-sc-tzxe02-0 cuLnRd" src="{{r.pro_image.url}}" alt="D DRYL SUSPENSION">
        
            <p class="Text-sc-uzvrb9-0 guRpbr">{{r.name}}</p>
          </a>
        
        </div>
      </div>
        {% endfor %}
        </div>
      </div>
</section> 

{% endblock main-content %}

FranchiseApp/templates/mitsheathcare/products.html
{% extends 'mitsheathcare/mitscore/core.html' %}
{% load static %}
{% block title %}Products{% endblock title %}
{% block main-content %}

<section >
  <div class="container-fluid mt-5 "  > 
       <h1 class="text-center text-white " style="box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);background-color:{{comp.Company_color2}};">Our Products</h1>
         <div class="mt-5 ml-5">
       <h4 class="text-center">Total Products : {{total_issues}}</h4>
       <input id="myInput" type="search" placeholder="Search For Molecules..." class=" form-control w-50 mx-auto" style="border:3px solid {{comp.Company_color1}};;"> 
      </div>
       <div class="col-lg-12 col-md-12 mt-5">
           <div class="row">
            {% for p in product %}
               <div class=" col-lg-4 col-md-12 col-12" id="myTab">
                  <div class="card1 card align-items-center effect " style="max-width: 540px;height: 150px;">
                  <a href="{% url 'FranchiseApp:Productdetail' p.id %}">
                        <img src="{{p.pro_image.url}}" alt="..." class="p-3">
                        <div class="card-body p-0">
                          <h6 class="card-title ">{{p.name}}</h6>
                          <small class="card-text text-muted" >{{p.description}}</small>
                        </a>
                     </div>
                      </div>
                      </div>
                      {% endfor %}
                  </div>
      </div>
      </div>
   </section>
{% endblock main-content %}